### ISSUE TITLE
VTail conversion

### ISSUE THREAD

**Issue by erwinf** [phochan/Hee-Wing-T1-VTOL#2]
Thanks for sharing your mods. Can you also make a conversion tail assembly for vtail? Since differential thrust is not that effective for the t-1. Maybe making it to a vtail like the zmo vtol will help with the yaw control.

**Comment by JulianGoesPro** [comment]
Why would you prefer a vtail conversion instead of just adding a servo and a hinge to the ruder?

**Comment by erwinf** [comment]
Actually, i plan on doing that as well. Thr vtail conversion is for just in case adding a working rudder doesn't work.
